apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      resource: memory
  template:
    metadata:
      labels:
        resource: memory
    spec:
      containers:
        - name: back-container
          image: kimhyeonkyun123/backk8sjenkins:1.VERSION
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            successThreshold: 3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 1Gi
            limits:
              memory: 2Gi
          env:
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: back-config
                  key: CONFIG_SERVER
            - name: APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: back-config
                  key: APPLICATION_NAME
            - name: APPLICATION_ENV
              valueFrom:
                configMapKeyRef:
                  name: back-config
                  key: APPLICATION_ENV
      terminationGracePeriodSeconds: 5
